export interface JevDemo {
  id: string
  title: string
  description: string
  href: string
  image: string
  links?: { label: string; href: string }[]
}

export const jevDemos: JevDemo[] = [
  {
    id: 'semanticspace',
    title: 'SemanticSpace',
    description: 'Invent axes; Jev places phrases.',
    href: 'https://semanticspace.dev/',
    image: '/jev-gallery/01-semanticspace.png',
  },
  {
    id: 'jev-ultrafast',
    title: 'Jev Ultrafast',
    description: 'Browser Use flights ~7s / ~$0.0039.',
    href: 'https://github.com/browser-use/jev-ultrafast',
    image: '/jev-gallery/browser-use-demo.gif',
    links: [
      { label: 'Tweet', href: 'https://x.com/gregpr07/status/2100411066966749359' },
    ],
  },
  {
    id: 'typewriter',
    title: 'Typewriter',
    description: 'Live judgments as you type.',
    href: 'https://typesafe-demo.val.run/',
    image: '/jev-gallery/02-typewriter.png',
  },
  {
    id: 'crowdcheck',
    title: 'Crowdcheck',
    description: '~10k synthetic personas.',
    href: 'https://crowdcheck-ai.vercel.app/',
    image: '/jev-gallery/03-crowdcheck.png',
  },
  {
    id: 'music-lab',
    title: 'Music Lab',
    description: 'Jev picks enums; code renders music.',
    href: 'https://jev-playground.vercel.app/music/',
    image: '/jev-gallery/05-music.png',
  },
  {
    id: 'jev-search',
    title: 'Jev Search',
    description: 'Typed search judgments.',
    href: 'https://jev.s1.dev/',
    image: '/jev-gallery/04-jev-search.png',
  },
  {
    id: 'jev-trader',
    title: 'jev-trader',
    description: 'Buy/sell every Monad block.',
    href: 'https://jev-trader.vercel.app/',
    image: '/jev-gallery/08-trader.png',
  },
  {
    id: 'smart-home',
    title: 'Smart-home Fan-out',
    description: 'Official pattern demo.',
    href: 'https://docs.typesafe.ai/demos/smart-home',
    image: '/jev-gallery/07-smart-home.png',
  },
  {
    id: 'doom-wikiracing',
    title: 'Doom + Wikiracing',
    description: 'Launch demos.',
    href: 'https://typesafe.ai/blog/introducing-system-one-models-and-jev',
    image: '/jev-gallery/13-typesafe-blog.png',
  },
  {
    id: 'jevplayground',
    title: 'No-signup Playground',
    description: 'Try Jev instantly.',
    href: 'https://jevplayground.com/',
    image: '/jev-gallery/06-jevplayground.png',
  },
  {
    id: 'jev-chess',
    title: 'Jev Chess',
    description: 'AI chess with typed moves.',
    href: 'https://jev-chess-master.vercel.app/',
    image: '/jev-gallery/07-smart-home.png',
  },
  {
    id: 'pitch-jev',
    title: 'Pitch Jev',
    description: 'Practice your pitch with Jev.',
    href: 'https://pitchjev.vercel.app/',
    image: '/jev-gallery/06-jevplayground.png',
  },
  {
    id: 'fast-jev-compaction',
    title: 'Fast Jev Compaction',
    description: 'Score tool traces; keep what matters.',
    href: 'https://github.com/tamaratran/fast-jev-compaction',
    image: '/jev-gallery/14-fast-jev-compaction.png',
  },
  {
    id: 'mobile-jev',
    title: 'Mobile Jev',
    description: 'Jev navigates a real Android phone.',
    href: 'https://github.com/droidrun/mobile-jev',
    image: '/jev-gallery/15-mobile-jev.png',
  },
  {
    id: 'jev-experiments',
    title: 'Jev Experiments',
    description: 'Latency-first demos and benchmarks.',
    href: 'https://github.com/dabit3/jev-experiments',
    image: '/jev-gallery/16-jev-experiments.png',
  },
  {
    id: 'jev-review',
    title: 'Jev Review',
    description: 'Staged code review with a dashboard.',
    href: 'https://github.com/devagrawal09/jev-review',
    image: '/jev-gallery/17-jev-review.png',
  },
  {
    id: 'jev-foreman',
    title: 'Jev Foreman',
    description: 'Jev runs a software factory.',
    href: 'https://github.com/thruwire/foreman',
    image: '/jev-gallery/18-jev-foreman.png',
  },
  {
    id: 'pg-jev',
    title: 'pg-jev',
    description: 'Ask Postgres tables in plain language.',
    href: 'https://pgjev.com',
    image: '/jev-gallery/19-pg-jev.png',
  },
  {
    id: 'perch',
    title: 'Perch',
    description: 'Semantic code linting with Jev.',
    href: 'https://perchscan.com',
    image: '/jev-gallery/20-perch.png',
  },
  {
    id: 'jev-mcp',
    title: 'Jev MCP',
    description: 'Typed Jev judgments for any agent.',
    href: 'https://github.com/jkudish/jev-mcp',
    image: '/jev-gallery/21-jev-mcp.png',
  },
  {
    id: 'jev-browser',
    title: 'Jev Browser',
    description: 'Jev chooses browser actions.',
    href: 'https://github.com/jkudish/jev-browser',
    image: '/jev-gallery/22-jev-browser.png',
  },
  {
    id: 'jev-voice-browser',
    title: 'Jev Voice Browser',
    description: 'Speak; Jev drives Playwright.',
    href: 'https://github.com/moritzkremb/jev-voice-browser',
    image: '/jev-gallery/23-jev-voice-browser.png',
  },
  {
    id: 'typesafe-mario',
    title: 'TypeSafe Mario',
    description: 'Jev plays Mario from emulator state.',
    href: 'https://github.com/fhshaik/typesafe-mario',
    image: '/jev-gallery/24-typesafe-mario.png',
  },
  {
    id: 'jevpilot',
    title: 'JevPilot',
    description: 'Typed decisions drive a 3D car.',
    href: 'https://jevpilot.standardagents.ai',
    image: '/jev-gallery/25-jevpilot.png',
  },
  {
    id: 'tax-doc-classifier',
    title: 'Tax Doc Classifier',
    description: 'Classify IRS forms with Jev.',
    href: 'https://github.com/kyotofin/tax-doc-classifier',
    image: '/jev-gallery/26-tax-doc-classifier.png',
  },
  {
    id: 'jev-trade',
    title: 'Jev Trade',
    description: 'Live Jev trader on Hyperliquid.',
    href: 'https://jev-trade.com',
    image: '/jev-gallery/27-jev-trade.png',
  },
  {
    id: 'jev-shell-history',
    title: 'Jev Shell History',
    description: 'Rank shell suggestions by meaning.',
    href: 'https://github.com/mrnugget/jev-shell-history',
    image: '/jev-gallery/28-jev-shell-history.png',
  },
  {
    id: 'jev-pruner',
    title: 'Jev Pruner',
    description: 'Trim noisy Bash output for agents.',
    href: 'https://github.com/tamaratran/jev-pruner',
    image: '/jev-gallery/29-jev-pruner.png',
  },
  {
    id: 'jev-router',
    title: 'Jev Router',
    description: 'Route Claude tasks to cheaper models.',
    href: 'https://github.com/gargpratyush/jev-router',
    image: '/jev-gallery/30-jev-router.png',
  },
  {
    id: 'neo4jev',
    title: 'Neo4Jev',
    description: 'Navigate graph edges with Jev.',
    href: 'https://github.com/jexp/neo4jev',
    image: '/jev-gallery/31-neo4jev.png',
  },
]
